# Generated by Django 5.1.3 on 2024-12-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Rajasthan', 'Rajasthan'), ('Puducherry', 'Puducherry'), ('Chattisgarh', 'Chattisgarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Delhi', 'Delhi'), ('Assam', 'Assam'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Haryana', 'Haryana'), ('Sikkim', 'Sikkim'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Uttarakhand', 'Uttarakhand'), ('Goa', 'Goa'), ('Bangladesh', 'Bangladesh'), ('Daman and Diu', 'Daman and Diu'), ('Tamil Nadu', 'Tamil Nadu'), ('West Bengal', 'West Bengal'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Punjab', 'Punjab'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Odisha', 'Odisha'), ('Gujarat', 'Gujarat')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('CZ', 'Cheese'), ('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('ML', 'Milk'), ('PN', 'Paneer'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
