# Generated by Django 5.1.3 on 2024-12-12 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_city_alter_customer_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Puducherry', 'Puducherry'), ('Daman and Diu', 'Daman and Diu'), ('Rajasthan', 'Rajasthan'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Punjab', 'Punjab'), ('Telangana', 'Telangana'), ('Bangladesh', 'Bangladesh'), ('Odisha', 'Odisha'), ('Sikkim', 'Sikkim'), ('Gujarat', 'Gujarat'), ('Chandigarh', 'Chandigarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('West Bengal', 'West Bengal'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Chattisgarh', 'Chattisgarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Uttarakhand', 'Uttarakhand'), ('Tripura', 'Tripura'), ('Bihar', 'Bihar'), ('Tamil Nadu', 'Tamil Nadu'), ('Goa', 'Goa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('CR', 'Curd'), ('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('ML', 'Milk'), ('PN', 'Paneer'), ('MS', 'Milkshake')], max_length=2),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
