# Generated by Django 5.1.3 on 2024-12-12 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_state_alter_product_category_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Rajasthan', 'Rajasthan'), ('Telangana', 'Telangana'), ('Daman and Diu', 'Daman and Diu'), ('Chattisgarh', 'Chattisgarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Punjab', 'Punjab'), ('Uttarakhand', 'Uttarakhand'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Odisha', 'Odisha'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Goa', 'Goa'), ('Bangladesh', 'Bangladesh'), ('Delhi', 'Delhi'), ('Haryana', 'Haryana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('West Bengal', 'West Bengal'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Tripura', 'Tripura'), ('Gujarat', 'Gujarat'), ('Puducherry', 'Puducherry'), ('Sikkim', 'Sikkim'), ('Uttar Pradesh', 'Uttar Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LS', 'Lassi'), ('MS', 'Milkshake'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CR', 'Curd'), ('IC', 'Ice-Creams'), ('ML', 'Milk')], max_length=2),
        ),
    ]
