# Generated by Django 5.1.3 on 2024-12-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customer_state_alter_product_category_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('PayPal', 'PayPal'), ('SSLcommerz', 'SSLcommerz')], default='Cash on Delivery', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Puducherry', 'Puducherry'), ('Tamil Nadu', 'Tamil Nadu'), ('Bangladesh', 'Bangladesh'), ('Haryana', 'Haryana'), ('Telangana', 'Telangana'), ('Punjab', 'Punjab'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Delhi', 'Delhi'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Odisha', 'Odisha'), ('Chandigarh', 'Chandigarh'), ('Uttarakhand', 'Uttarakhand'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Sikkim', 'Sikkim'), ('Chattisgarh', 'Chattisgarh'), ('Tripura', 'Tripura'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Rajasthan', 'Rajasthan'), ('West Bengal', 'West Bengal'), ('Daman and Diu', 'Daman and Diu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('LS', 'Lassi'), ('ML', 'Milk'), ('GH', 'Ghee'), ('CR', 'Curd'), ('IC', 'Ice-Creams'), ('PN', 'Paneer'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
