# Generated by Django 5.1.3 on 2024-12-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customer_state_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_id',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_status',
            new_name='payment_status',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chattisgarh', 'Chattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Goa', 'Goa'), ('Punjab', 'Punjab'), ('Chandigarh', 'Chandigarh'), ('Rajasthan', 'Rajasthan'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Sikkim', 'Sikkim'), ('Delhi', 'Delhi'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Assam', 'Assam'), ('Tamil Nadu', 'Tamil Nadu'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Tripura', 'Tripura'), ('Bangladesh', 'Bangladesh'), ('Telangana', 'Telangana'), ('Odisha', 'Odisha'), ('Gujarat', 'Gujarat'), ('Daman and Diu', 'Daman and Diu'), ('Bihar', 'Bihar'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Puducherry', 'Puducherry'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('West Bengal', 'West Bengal'), ('Uttarakhand', 'Uttarakhand')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Creams'), ('GH', 'Ghee'), ('MS', 'Milkshake'), ('ML', 'Milk'), ('PN', 'Paneer'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
