# Generated by Django 5.1.3 on 2024-12-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_razorpay_order_id_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Tripura', 'Tripura'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Tamil Nadu', 'Tamil Nadu'), ('Rajasthan', 'Rajasthan'), ('Bangladesh', 'Bangladesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Chattisgarh', 'Chattisgarh'), ('Assam', 'Assam'), ('Delhi', 'Delhi'), ('Telangana', 'Telangana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa'), ('Odisha', 'Odisha'), ('Gujarat', 'Gujarat'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Sikkim', 'Sikkim'), ('Puducherry', 'Puducherry'), ('Bihar', 'Bihar'), ('Haryana', 'Haryana'), ('Punjab', 'Punjab')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('IC', 'Ice-Creams'), ('PN', 'Paneer'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
