# Generated by Django 5.1.3 on 2024-12-14 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_product_orderplaced_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Chattisgarh', 'Chattisgarh'), ('Assam', 'Assam'), ('Delhi', 'Delhi'), ('Bangladesh', 'Bangladesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Punjab', 'Punjab'), ('Puducherry', 'Puducherry'), ('Chandigarh', 'Chandigarh'), ('Rajasthan', 'Rajasthan'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Odisha', 'Odisha'), ('Himachal Pradesh', 'Himachal Pradesh'), ('West Bengal', 'West Bengal'), ('Uttarakhand', 'Uttarakhand'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Haryana', 'Haryana'), ('Gujarat', 'Gujarat'), ('Tripura', 'Tripura'), ('Telangana', 'Telangana'), ('Tamil Nadu', 'Tamil Nadu'), ('Sikkim', 'Sikkim'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Goa', 'Goa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('ML', 'Milk'), ('CZ', 'Cheese'), ('GH', 'Ghee'), ('CR', 'Curd'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('PN', 'Paneer')], max_length=2),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
