# Generated by Django 5.1.3 on 2024-12-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customer_state_alter_product_category_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Uttarakhand', 'Uttarakhand'), ('Goa', 'Goa'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Bangladesh', 'Bangladesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Telangana', 'Telangana'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chattisgarh', 'Chattisgarh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Bihar', 'Bihar'), ('Rajasthan', 'Rajasthan'), ('Odisha', 'Odisha'), ('Tripura', 'Tripura'), ('Chandigarh', 'Chandigarh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('West Bengal', 'West Bengal'), ('Tamil Nadu', 'Tamil Nadu'), ('Haryana', 'Haryana'), ('Daman and Diu', 'Daman and Diu'), ('Sikkim', 'Sikkim'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Gujarat', 'Gujarat'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Delhi', 'Delhi'), ('Assam', 'Assam')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('CZ', 'Cheese'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('ML', 'Milk'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
