# Generated by Django 5.1.3 on 2024-12-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_customer_state_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='Product',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Telangana', 'Telangana'), ('Delhi', 'Delhi'), ('Puducherry', 'Puducherry'), ('Haryana', 'Haryana'), ('Bangladesh', 'Bangladesh'), ('Gujarat', 'Gujarat'), ('Chattisgarh', 'Chattisgarh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Tripura', 'Tripura'), ('Bihar', 'Bihar'), ('Daman and Diu', 'Daman and Diu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Chandigarh', 'Chandigarh'), ('Assam', 'Assam'), ('Odisha', 'Odisha'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Rajasthan', 'Rajasthan'), ('Tamil Nadu', 'Tamil Nadu'), ('Uttarakhand', 'Uttarakhand'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('West Bengal', 'West Bengal'), ('Sikkim', 'Sikkim'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Punjab', 'Punjab')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LS', 'Lassi'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('CR', 'Curd'), ('PN', 'Paneer'), ('ML', 'Milk'), ('GH', 'Ghee'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
