# Generated by Django 5.1.3 on 2024-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_customer_state_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Tamil Nadu', 'Tamil Nadu'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Sikkim', 'Sikkim'), ('Puducherry', 'Puducherry'), ('Gujarat', 'Gujarat'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Odisha', 'Odisha'), ('Assam', 'Assam'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Punjab', 'Punjab'), ('Goa', 'Goa'), ('Telangana', 'Telangana'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Bihar', 'Bihar'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('Rajasthan', 'Rajasthan'), ('Chattisgarh', 'Chattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('West Bengal', 'West Bengal'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Bangladesh', 'Bangladesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('CR', 'Curd'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
