# Generated by Django 5.1.3 on 2024-12-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_product_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Tamil Nadu', 'Tamil Nadu'), ('Haryana', 'Haryana'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Delhi', 'Delhi'), ('Bangladesh', 'Bangladesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Odisha', 'Odisha'), ('Gujarat', 'Gujarat'), ('Assam', 'Assam'), ('Tripura', 'Tripura'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Sikkim', 'Sikkim'), ('Chattisgarh', 'Chattisgarh'), ('Uttarakhand', 'Uttarakhand'), ('Bihar', 'Bihar'), ('Telangana', 'Telangana'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Punjab', 'Punjab'), ('Chandigarh', 'Chandigarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Rajasthan', 'Rajasthan'), ('Goa', 'Goa'), ('Puducherry', 'Puducherry'), ('West Bengal', 'West Bengal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('ML', 'Milk'), ('IC', 'Ice-Creams'), ('CR', 'Curd'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
